kind: pipeline
name: drone-ecr-registry-plugin

workspace:
  base: /go
  path: src/github.com/davidbyttow/drone-ecr-registry-plugin

steps:
- name: test
  image: golang:latest
  environment:
  commands:
    - GO111MODULE=on go test -v ./...
  when:
    event:
      - push
      - pull_request

- name: build
  image: golang:latest
  commands:
    - make build
  when:
    event:
      - push
      - pull_request

- name: publish
  image: ueniltd/kaniko
  pull: always
  settings:
    image_name: 362870652376.dkr.ecr.eu-central-1.amazonaws.com/drone-ecr-registry-plugin
    cache: true
    dockerfile: docker/Dockerfile
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
  when:
    event:
      - push
      - tag
    branch:
      - master
